### PR TITLE
Indonesian added

### PR DESCRIPTION
**Pull request by Ben1980**
This is resolving issue #5.

### CODE REVIEW

**Comment by Ben1980** [comment]
@wangzhipeng-vicky please check if the Indonesian translation is correct to resolve #5.

**Comment by wangzhipeng-vicky** [comment]
> @wangzhipeng-vicky please check if the Indonesian translation is correct to resolve #5.

I'm using version 1.2.0, it doesn't seem to work,

**Comment by Ben1980** [comment]
@wangzhipeng-vicky that wasn't my intention. I asked you to review the code change to validate if the Indonesian translation is correct before I merge this into main and release v1.3.

**Comment by wangzhipeng-vicky** [comment]
> @wangzhipeng-vicky that wasn't my intention. I asked you to review the code change to validate if the Indonesian translation is correct before I merge this into main and release v1.3.

I took a look. It's what I need

**Pull request merged**
